env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
- '@typescript-eslint'
parser: '@typescript-eslint/parser'
rules: {}
